sudo: required
dist: trusty
language: node_js
node_js:
- '9'
install: true
script: echo no build needed
deploy:
  provider: npm
  email: bryphe@outlook.com
  skip_cleanup: true
  api_key:
    secure: oKi+rOeEY/u4LGteZhCQMQF5mkj2iOpO3oTfFvaPa4mIdXWnbBFtrMF7ihi6ah+PoEpx9u4nVaB0xBOrLczElyQa8HyXFyWpy2fZOFKwQWRemufzqJIoJx5u8YHTmi4EcSATblqIBp6VFVP/3g+za27Dh1klOSTR8iiSuM1FHtAEfBaptjwvQnJX9WhOiAes65FalVwR7a5fwDfe8bqHxU++qbvcY+YM5KYt/wKK3FZEoSjY1FY4n2Rx8wDEeuR/ZinESOHz/ho2NBcnSsQkBRqdgQ/MF/169EOypql22DTDAitGurXWAHcyazuIRC3p1uD88ZnuizVjAf2RW7Agm1GFFO7vkBiLhwZCmTq7daq+exr5JdOU3+sptiDx1BvQ8LInZDAlB7vP5CNlyDcd50EGXW51D4lnZ8lgl+p1nyfr7WeLBnWbEG0KTlNW9EA44P4eYOuhGTlnRv03xarsAr900994QKK3JmUESFfHcAgLoGibZyBXphxY0sLMbPW9nxqCMhLUKAKH02i/O5FCJkFUKYLr+peJnju0IPzewDJizGkGH6nuZlvWsWWJM285btrpx3MOWaOVkXU+/81Hk1Aj/Klw9J/3dPIj7hk4bQK9+Jk5VdPT27m1tMnniadHKfMIs8yI2+F5t3bpZ8qna3MHjR8qlsaAQ8Kh+HSjUMc=
  on:
    repo: onivim/oni-neovim-binaries
